# -*- coding: utf-8 -*-
"""CountingFail.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_RXzV8YHmlb4_9tr_UbRq3gKSgVV9ah1
"""

print("Hello Wrold")